# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import webchela.core.protobuf.webchela_pb2 as webchela__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLoad = channel.unary_unary(
                '/webchela.Server/GetLoad',
                request_serializer=webchela__pb2.Empty.SerializeToString,
                response_deserializer=webchela__pb2.Load.FromString,
                )
        self.RunTask = channel.unary_stream(
                '/webchela.Server/RunTask',
                request_serializer=webchela__pb2.Task.SerializeToString,
                response_deserializer=webchela__pb2.Chunk.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoad,
                    request_deserializer=webchela__pb2.Empty.FromString,
                    response_serializer=webchela__pb2.Load.SerializeToString,
            ),
            'RunTask': grpc.unary_stream_rpc_method_handler(
                    servicer.RunTask,
                    request_deserializer=webchela__pb2.Task.FromString,
                    response_serializer=webchela__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webchela.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/webchela.Server/GetLoad',
            webchela__pb2.Empty.SerializeToString,
            webchela__pb2.Load.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webchela.Server/RunTask',
            webchela__pb2.Task.SerializeToString,
            webchela__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
