# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webchela.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='webchela.proto',
  package='webchela',
  syntax='proto3',
  serialized_options=b'Z\n.;webchela',
  serialized_pb=b'\n\x0ewebchela.proto\x12\x08webchela\"#\n\x05\x43hunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty\"9\n\x04Load\x12\x10\n\x08\x63pu_load\x18\x01 \x01(\x05\x12\x10\n\x08mem_free\x18\x02 \x01(\x03\x12\r\n\x05score\x18\x03 \x01(\x05\"\x9e\x01\n\x06Result\x12\x0c\n\x04UUID\x18\x01 \x01(\t\x12\x10\n\x08page_url\x18\x02 \x01(\t\x12\x12\n\npage_title\x18\x03 \x01(\t\x12\x11\n\tpage_body\x18\x04 \x01(\t\x12\x15\n\rscript_output\x18\x05 \x03(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x13\n\x0bstatus_code\x18\x07 \x01(\x05\x12\x14\n\x0c\x63ontent_type\x18\x08 \x01(\t\"\xe4\x02\n\x04Task\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\'\n\x07\x62rowser\x18\x02 \x01(\x0b\x32\x16.webchela.Task.Browser\x12\x0c\n\x04urls\x18\x03 \x03(\t\x12\x0f\n\x07scripts\x18\x04 \x03(\t\x12\x12\n\nchunk_size\x18\x05 \x01(\x03\x12\x10\n\x08\x63pu_load\x18\x06 \x01(\x05\x12\x10\n\x08mem_free\x18\x07 \x01(\x03\x12\x0f\n\x07timeout\x18\x08 \x01(\x05\x1a\xb7\x01\n\x07\x42rowser\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x61rgument\x18\x02 \x03(\t\x12\x11\n\textension\x18\x03 \x03(\t\x12\x10\n\x08geometry\x18\x04 \x01(\t\x12\x10\n\x08instance\x18\x05 \x01(\x05\x12\x14\n\x0cinstance_tab\x18\x06 \x01(\x05\x12\x11\n\tpage_size\x18\x07 \x01(\x03\x12\x14\n\x0cpage_timeout\x18\x08 \x01(\x05\x12\x16\n\x0escript_timeout\x18\t \x01(\x05\x32\x66\n\x06Server\x12,\n\x07GetLoad\x12\x0f.webchela.Empty\x1a\x0e.webchela.Load\"\x00\x12.\n\x07RunTask\x12\x0e.webchela.Task\x1a\x0f.webchela.Chunk\"\x00\x30\x01\x42\x0cZ\n.;webchelab\x06proto3'
)




_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='webchela.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='webchela.Chunk.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='webchela.Chunk.end', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=63,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='webchela.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=72,
)


_LOAD = _descriptor.Descriptor(
  name='Load',
  full_name='webchela.Load',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_load', full_name='webchela.Load.cpu_load', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_free', full_name='webchela.Load.mem_free', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='webchela.Load.score', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=131,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='webchela.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UUID', full_name='webchela.Result.UUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_url', full_name='webchela.Result.page_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_title', full_name='webchela.Result.page_title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_body', full_name='webchela.Result.page_body', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script_output', full_name='webchela.Result.script_output', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='webchela.Result.url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='webchela.Result.status_code', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_type', full_name='webchela.Result.content_type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=292,
)


_TASK_BROWSER = _descriptor.Descriptor(
  name='Browser',
  full_name='webchela.Task.Browser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='webchela.Task.Browser.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='argument', full_name='webchela.Task.Browser.argument', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extension', full_name='webchela.Task.Browser.extension', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='webchela.Task.Browser.geometry', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance', full_name='webchela.Task.Browser.instance', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance_tab', full_name='webchela.Task.Browser.instance_tab', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='webchela.Task.Browser.page_size', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_timeout', full_name='webchela.Task.Browser.page_timeout', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script_timeout', full_name='webchela.Task.Browser.script_timeout', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=651,
)

_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='webchela.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='webchela.Task.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='browser', full_name='webchela.Task.browser', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urls', full_name='webchela.Task.urls', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scripts', full_name='webchela.Task.scripts', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_size', full_name='webchela.Task.chunk_size', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_load', full_name='webchela.Task.cpu_load', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_free', full_name='webchela.Task.mem_free', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='webchela.Task.timeout', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TASK_BROWSER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=651,
)

_TASK_BROWSER.containing_type = _TASK
_TASK.fields_by_name['browser'].message_type = _TASK_BROWSER
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Load'] = _LOAD
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Task'] = _TASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'webchela_pb2'
  # @@protoc_insertion_point(class_scope:webchela.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'webchela_pb2'
  # @@protoc_insertion_point(class_scope:webchela.Empty)
  })
_sym_db.RegisterMessage(Empty)

Load = _reflection.GeneratedProtocolMessageType('Load', (_message.Message,), {
  'DESCRIPTOR' : _LOAD,
  '__module__' : 'webchela_pb2'
  # @@protoc_insertion_point(class_scope:webchela.Load)
  })
_sym_db.RegisterMessage(Load)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'webchela_pb2'
  # @@protoc_insertion_point(class_scope:webchela.Result)
  })
_sym_db.RegisterMessage(Result)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {

  'Browser' : _reflection.GeneratedProtocolMessageType('Browser', (_message.Message,), {
    'DESCRIPTOR' : _TASK_BROWSER,
    '__module__' : 'webchela_pb2'
    # @@protoc_insertion_point(class_scope:webchela.Task.Browser)
    })
  ,
  'DESCRIPTOR' : _TASK,
  '__module__' : 'webchela_pb2'
  # @@protoc_insertion_point(class_scope:webchela.Task)
  })
_sym_db.RegisterMessage(Task)
_sym_db.RegisterMessage(Task.Browser)


DESCRIPTOR._options = None

_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='webchela.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=653,
  serialized_end=755,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLoad',
    full_name='webchela.Server.GetLoad',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_LOAD,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunTask',
    full_name='webchela.Server.RunTask',
    index=1,
    containing_service=None,
    input_type=_TASK,
    output_type=_CHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
